### ISSUE TITLE
Corrections and additions

### ISSUE THREAD

**Issue by kgherdeg** [brentspector/reborn-pokepedia#27]
Love the tool, noticed a couple of areas for update. Will add as I discover.

For ZEL/Pulse Tangrowth, you had Wigglytuff as an available Pokemon due to being able to find a moon stone, but don't include Musharna or Delcatty who are also available and can evolve via Moon Stone.

Additionally, you list Happiny as being available but you cannot access the house to get the key until after the PULSE is defeated.

**Comment by kgherdeg** [comment]
(The latter point is incorrect, I've come to find out - but the first point still stands)

**Comment by brentspector** [comment]
Thanks! I see Musharna on the list (closer to the bottom since it's got a high pokedex number)

Thanks for catching Delcatty! I forgot the event moved from Coral Ward to Peridot Ward and thought it got axed outright.
